### ISSUE TITLE
error encountered in running 'npm run dev'

### ISSUE THREAD

**Issue by ciphercharly** [garbados/p2p-social-bookmarking#4]
(I barely know what I'm doing so this could be irrelevant and only my fault)

this is npm-debug.log 

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:js' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild:js', 'build:js', 'postbuild:js' ]
5 info lifecycle p2p-social-bookmarking@1.0.0-alpha~prebuild:js: p2p-social-bookmarking@1.0.0-alpha
6 silly lifecycle p2p-social-bookmarking@1.0.0-alpha~prebuild:js: no script for prebuild:js, continuing
7 info lifecycle p2p-social-bookmarking@1.0.0-alpha~build:js: p2p-social-bookmarking@1.0.0-alpha
8 verbose lifecycle p2p-social-bookmarking@1.0.0-alpha~build:js: unsafe-perm in lifecycle true
9 verbose lifecycle p2p-social-bookmarking@1.0.0-alpha~build:js: PATH: /usr/share/npm/bin/node-gyp-bin:~/Desktop/p2p-social-bookmarking/node_modules/.bin:/usr/share/npm/bin/node-gyp-bin:~/Desktop/p2p-social-bookmarking/node_modules/.bin:/usr/share/npm/bin/node-gyp-bin:~/Desktop/p2p-social-bookmarking/node_modules/.bin:/usr/local/go/bin:~/anaconda2/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:~/bin
10 verbose lifecycle p2p-social-bookmarking@1.0.0-alpha~build:js: CWD: ~/Desktop/p2p-social-bookmarking
11 silly lifecycle p2p-social-bookmarking@1.0.0-alpha~build:js: Args: [ '-c',
11 silly lifecycle   'browserify src/js/index.js -o build/app.js -t [ babelify ]' ]
12 silly lifecycle p2p-social-bookmarking@1.0.0-alpha~build:js: Returned: code: 1  signal: null
13 info lifecycle p2p-social-bookmarking@1.0.0-alpha~build:js: Failed to exec build:js script
14 verbose stack Error: p2p-social-bookmarking@1.0.0-alpha build:js: `browserify src/js/index.js -o build/app.js -t [ babelify ]`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid p2p-social-bookmarking@1.0.0-alpha
16 verbose cwd ~/Desktop/p2p-social-bookmarking
17 error Linux 4.15.0-34-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build:js"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error p2p-social-bookmarking@1.0.0-alpha build:js: `browserify src/js/index.js -o build/app.js -t [ babelify ]`
22 error Exit status 1
23 error Failed at the p2p-social-bookmarking@1.0.0-alpha build:js script 'browserify src/js/index.js -o build/app.js -t [ babelify ]'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the p2p-social-bookmarking package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     browserify src/js/index.js -o build/app.js -t [ babelify ]
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs p2p-social-bookmarking
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls p2p-social-bookmarking
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by garbados** [comment]
Huh! I'm not sure what the issue is. This seems suspicious:
```
8 verbose lifecycle p2p-social-bookmarking@1.0.0-alpha~dev: unsafe-perm in lifecycle true
```
